### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by Intevel** [johannschopplich/unjwt#2]
Hey! I get an `No "exports" main` defined error from `unjwt` when bundling with esbuild

**Comment by johannschopplich** [comment]
What's your project's package type – CJS or ESM? I don't build CJS at the moment.

For ESM; the exports [seem correct](https://arethetypeswrong.github.io/?p=unjwt%400.2.1).

**Comment by Intevel** [comment]
Currently CJS
